feat: append nomad task mounts
hashicorp/nomad-driver-podman pull request #152
Opened 2022-01-23 12:21 UTC by ttys3

something like this: https://github.com/hashicorp/waypoint/blob/566c65afb74fcfe64f3f0e50ef7eddbd03d9a3c8/internal/serverinstall/nomad.go#L914

will always fail when using the podman driver, because the driver does not handle this mounts now.

this PR fixup it

2022-01-23 12:22 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad-driver-podman?pullRequest=152)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad-driver-podman?pullRequest=152)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad-driver-podman?pullRequest=152).</sub>

2022-02-06 17:19 UTC, ttys3 commented
@lgfa29  can you review this ?

2022-02-15 23:15 UTC, lgfa29 requested changes
Thanks for the PR @ttys3, and sorry for the delay and getting it reviewed.

I did a quick test using host volumes and it all seems to work 🙂 

Would you mind adding some tests and a `CHANGELOG` entry?

2022-02-23 15:50 UTC, lgfa29 commented
Ah sorry, I mean like automated testing 😅 

Something like this one, to verify that the configuration is properly set in the driver:
https://github.com/hashicorp/nomad-driver-podman/blob/v0.3.0/driver_test.go#L1225-L1232

You may need to update the `client.hcl` example config file to add a host volume:
https://github.com/hashicorp/nomad-driver-podman/blob/main/examples/nomad/client.hcl

2022-02-26 15:40 UTC, ttys3 commented
Ok, I'll figure a way to write some test.

2022-03-01 22:21 UTC, lgfa29 commented
> Ok, I'll figure a way to write some test.

Thanks! I linked to an example, but let me know if you need more help.

2022-05-31 20:44 UTC, lgfa29 commented
Oh shoot, I forgot about this PR and ended up merging https://github.com/hashicorp/nomad-driver-podman/pull/169, which does the same thing. I'm going to close this one but credit you in the CHANGELOG entry as well.

Sorry for that @ttys3  😞

2022-05-31 20:44 UTC, closed without merging

2022-06-01 09:35 UTC, ttys3 commented
@lgfa29 sorry for the **huge** delayed unit testing.

I checked the code, almost the same.

but what wondering me is that, I remember what block this PR is **missing unit testing**.

but I did not see any tests code in https://github.com/hashicorp/nomad-driver-podman/pull/169

2022-06-01 15:11 UTC, lgfa29 commented
Yeah, I wasn't paying enough attention when reviewing #169 😕 

Did you happen to find a way to test this?